PetBox geometry extended
next-exp/petalosim pull request #6
Opened 2021-11-05 20:01 UTC by carmenromo

This PR adds to the PetBox geometry a new conf parameter in order to have the possibility of choosing the type of tile in both planes of sensors. It also includes a new conf parameter to simulate either a single tile or the four tiles in the coincidence plane.

2021-11-05 20:02 UTC, carmenromo commented
Tests need to be updated and included. Work in progress.

2021-11-15 10:13 UTC, paolafer requested changes

2021-11-25 17:27 UTC, paolafer commented
This PR adds the current configuration of PETit; the tests pass and the code looks tidy, therefore I approve it!

2021-11-25 17:28 UTC, paolafer approved these changes

2021-11-25 17:28 UTC, merged